In [1]:
import pandas as pd
import numpy as np
import torch
import random
import os

from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer,
    DataCollatorWithPadding
)

from peft import get_peft_model, LoraConfig, TaskType

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_recall_fscore_support,
    matthews_corrcoef, balanced_accuracy_score,
    cohen_kappa_score, jaccard_score, hamming_loss,
    confusion_matrix
)


/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2025-06-20 07:12:56.637592: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-20 07:12:57.496800: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
202

In [3]:
import wandb
import optuna
import huggingface_hub

wandb.login(key="WANDB_KEY")
wandb.init(project="llama2_degendered", reinit=True)

huggingface_hub.login(token="HUGGINGFACE_TOKEN")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/hice1/mwesley32/.netrc


In [4]:
model_name = "meta-llama/Llama-2-7b-hf"
peft_cache_path = "../scratch/cache/llama2_degendered_hpo"

target_modules = ["q_proj", "v_proj", "k_proj", "o_proj"]

In [5]:
# Ensure 'data/combined_letters_degendered.csv' exists at the specified path
df = pd.read_csv("data/combined_letters_degendered.csv")[["full_text", "label"]].dropna()
df["label"] = df["label"].astype(int)

# Perform train-test split, stratifying by label to maintain class distribution
X_train, X_test, y_train, y_test = train_test_split(
    df["full_text"],
    df["label"],
    test_size=0.2,
    stratify=df["label"],
)

# The tokenizer is always loaded from the base model, as we need a fresh tokenizer for each run
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

In [6]:
# This function prepares your text data for the model by converting it into token IDs
from datasets import Dataset
def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding=False,
        max_length=512
    )
    tokens["labels"] = example["label"]
    return tokens

# Convert pandas Series to Hugging Face Dataset objects, then map the tokenization function
train_dataset = Dataset.from_dict({"text": X_train.tolist(), "label": y_train.tolist()})
test_dataset = Dataset.from_dict({"text": X_test.tolist(), "label": y_test.tolist()})

tokenized_train = train_dataset.map(tokenize, batched=True, num_proc=2).remove_columns(["text"])
tokenized_test = test_dataset.map(tokenize, batched=True, num_proc=2).remove_columns(["text"])

# Data Collator: Dynamically pads input sequences to the longest sequence in the batch
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

Map (num_proc=2):   0%|          | 0/7189 [00:00<?, ? examples/s]

Map (num_proc=2):   0%|          | 0/1798 [00:00<?, ? examples/s]

In [7]:
# Compute metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    preds = logits.argmax(-1)
    accuracy = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="weighted", zero_division=0)
    
    print("Confusion Matrix:\n", confusion_matrix(labels, preds))

    return {
        "f1_score": f1, 
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "mcc": matthews_corrcoef(labels, preds),
        "balanced_accuracy": balanced_accuracy_score(labels, preds),
        "cohen_kappa": cohen_kappa_score(labels, preds),
        "jaccard": jaccard_score(labels, preds, average="macro"),
        "hamming_loss": hamming_loss(labels, preds)
    }


In [8]:
def model_init_for_hpo(trial=None): # Make 'trial' parameter optional, defaulting to None
    # Load the base pre-trained model (Llama-2-7b-hf)
    base_model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2,
        id2label={0: "female", 1: "male"},
        label2id={"female": 0, "male": 1},
        cache_dir=peft_cache_path,
        device_map="auto"
    )
    base_model.config.pad_token_id = tokenizer.pad_token_id

    # Define LoRA hyperparameters if a trial is active,
    # otherwise fall back to a default/baseline configuration.
    if trial:
        lora_r = trial.suggest_int("lora_r", 8, 32, step=8)
        lora_alpha = trial.suggest_int("lora_alpha", lora_r * 2, lora_r * 4, step=lora_r)
        lora_dropout = trial.suggest_float("lora_dropout", 0.0, 0.2, step=0.05)
    else:
        lora_r = 8
        lora_alpha = 16
        lora_dropout = 0.1

    # Create the LoRA configuration for the current trial
    current_lora_config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        bias="none",
        task_type=TaskType.SEQ_CLS,
        target_modules=target_modules
    )

    # Apply PEFT (LoRA) to the base model
    peft_model = get_peft_model(base_model, current_lora_config)

    return peft_model

In [9]:
def optuna_hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True),
        "num_train_epochs": trial.suggest_int("num_train_epochs", 3, 10),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [2, 4, 8, 16]),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 0.03, step=0.01),
    }


In [10]:
training_args_for_hpo = TrainingArguments(
    output_dir="../scratch/hpo_results_llama2_degendered",
    per_device_eval_batch_size=8,
    fp16=True,
    save_strategy="steps",
    save_steps=500,
    logging_steps=50,
    report_to="wandb",
    remove_unused_columns=False,
    load_best_model_at_end=False,
    eval_strategy="epoch",
)

trainer = Trainer(
    model_init=model_init_for_hpo,
    args=training_args_for_hpo,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)


/tmp/ipykernel_1655097/916219255.py:14: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.


In [ ]:
best_run = trainer.hyperparameter_search(
    direction="maximize",
    backend="optuna",
    hp_space=optuna_hp_space,
    n_trials=30,
    storage="sqlite:///../scratch/optuna_llama2_gendered.db",
    study_name="llama2_degender_hpo",
    load_if_exists=True,
    compute_objective=lambda metrics: metrics["eval_f1_score"]
)

print("Best run details:")
print(best_run)

# Access the best hyperparameters found by Optuna
best_hps = best_run.hyperparameters
print("\nBest Hyperparameters Found:")
for hp, value in best_hps.items():
    print(f"  {hp}: {value}")

# W&B will provide a URL to the best run in its logs.
print(f"\nFind the best run and explore all trials in W&B at: {best_run.url}")

[I 2025-06-20 07:37:38,785] A new study created in RDB with name: llama2_degender_hpo


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,36.323500,49.500000,6.194000
2,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,36.292100,49.542000,6.200000
3,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,36.279600,49.560000,6.202000


Confusion Matrix:
 [[ 557    0]
 [1241    0]]
Confusion Matrix:
 [[ 557    0]
 [1241    0]]
Confusion Matrix:
 [[ 557    0]
 [1241    0]]


[I 2025-06-20 07:56:49,946] Trial 0 finished with value: 0.14654121470187445 and parameters: {'learning_rate': 0.0004370744612185534, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'weight_decay': 0.01, 'lora_r': 24, 'lora_alpha': 72, 'lora_dropout': 0.1}. Best is trial 0 with value: 0.14654121470187445.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁▁▁
eval/balanced_accuracy,▁▁▁
eval/cohen_kappa,▁▁▁
eval/f1_score,▁▁▁
eval/hamming_loss,▁▁▁
eval/jaccard,▁▁▁
eval/mcc,▁▁▁
eval/precision,▁▁▁
eval/recall,▁▁▁
eval/runtime,█▃▁
eval/samples_per_second,▁▆█


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.687900,1.054044,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.411800,49.380000,6.179000
2,1.218600,0.752412,0.594643,0.677976,0.604365,0.677976,0.049802,0.512906,0.033141,0.370262,0.322024,36.786800,48.876000,6.116000
3,0.945500,1.299526,0.575855,0.682425,0.586949,0.682425,0.015894,0.502770,0.007406,0.354153,0.317575,36.742200,48.936000,6.124000
4,0.348300,1.904724,0.598989,0.672970,0.601946,0.672970,0.050646,0.514722,0.037075,0.374094,0.327030,36.736600,48.943000,6.125000
5,0.309200,2.366466,0.616584,0.669077,0.614100,0.669077,0.082784,0.529219,0.070214,0.391513,0.330923,36.778600,48.887000,6.118000
6,0.123500,2.435754,0.619002,0.637931,0.609245,0.637931,0.084111,0.537826,0.082024,0.397277,0.362069,36.765800,48.904000,6.120000
7,0.023200,2.599640,0.624426,0.653504,0.615072,0.653504,0.094421,0.539707,0.089263,0.401308,0.346496,36.798400,48.861000,6.114000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]
Confusion Matrix:
 [[  44  513]
 [  66 1175]]
Confusion Matrix:
 [[  17  540]
 [  31 1210]]
Confusion Matrix:
 [[  55  502]
 [  86 1155]]
Confusion Matrix:
 [[  90  467]
 [ 128 1113]]
Confusion Matrix:
 [[153 404]
 [247 994]]
Confusion Matrix:
 [[ 134  423]
 [ 200 1041]]


[I 2025-06-20 08:55:56,309] Trial 1 finished with value: 0.6244258260138161 and parameters: {'learning_rate': 4.665582285029331e-05, 'num_train_epochs': 7, 'per_device_train_batch_size': 2, 'weight_decay': 0.03, 'lora_r': 32, 'lora_alpha': 64, 'lora_dropout': 0.05}. Best is trial 1 with value: 0.6244258260138161.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▆▇▆▅▁▃
eval/balanced_accuracy,▁▃▁▄▆██
eval/cohen_kappa,▁▄▂▄▇▇█
eval/f1_score,▁▅▂▅▇▇█
eval/hamming_loss,▁▃▂▃▄█▆
eval/jaccard,▁▄▂▅▇▇█
eval/loss,▂▁▃▅▇▇█
eval/mcc,▁▅▂▅▇▇█
eval/precision,▁▇▇▇███
eval/recall,█▆▇▆▅▁▃
eval/runtime,▁█▇▇█▇█


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.647300,0.686096,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.326600,49.495000,6.194000
2,0.674400,0.638261,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.364900,49.443000,6.187000
3,0.000000,nan,0.150057,0.311457,0.786341,0.311457,0.027389,0.501209,0.001499,0.156362,0.688543,36.353200,49.459000,6.189000
4,0.000000,nan,0.150057,0.311457,0.786341,0.311457,0.027389,0.501209,0.001499,0.156362,0.688543,36.337700,49.480000,6.192000
5,0.000000,nan,0.150057,0.311457,0.786341,0.311457,0.027389,0.501209,0.001499,0.156362,0.688543,36.326100,49.496000,6.194000
6,0.000000,nan,0.150057,0.311457,0.786341,0.311457,0.027389,0.501209,0.001499,0.156362,0.688543,36.335200,49.484000,6.192000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]
Confusion Matrix:
 [[   0  557]
 [   0 1241]]
Confusion Matrix:
 [[ 557    0]
 [1238    3]]
Confusion Matrix:
 [[ 557    0]
 [1238    3]]
Confusion Matrix:
 [[ 557    0]
 [1238    3]]
Confusion Matrix:
 [[ 557    0]
 [1238    3]]


[I 2025-06-20 09:41:08,563] Trial 2 finished with value: 0.1500571231464806 and parameters: {'learning_rate': 0.00017480221674484212, 'num_train_epochs': 6, 'per_device_train_batch_size': 4, 'weight_decay': 0.02, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05}. Best is trial 1 with value: 0.6244258260138161.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,██▁▁▁▁
eval/balanced_accuracy,▁▁████
eval/cohen_kappa,▁▁████
eval/f1_score,██▁▁▁▁
eval/hamming_loss,▁▁████
eval/jaccard,██▁▁▁▁
eval/loss,█▁
eval/mcc,▁▁████
eval/precision,▁▁████
eval/recall,██▁▁▁▁
eval/runtime,▁█▆▃▁▃


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.771700,0.753657,0.593384,0.658509,0.584327,0.658509,0.022287,0.507215,0.017750,0.368444,0.341491,36.820200,48.832000,6.111000
2,0.647600,0.687047,0.598243,0.657953,0.589650,0.657953,0.033281,0.511265,0.027397,0.373144,0.342047,36.817700,48.835000,6.111000
3,0.631700,0.678878,0.598088,0.651279,0.586817,0.651279,0.028982,0.510389,0.024846,0.373052,0.348721,36.816400,48.837000,6.111000


Confusion Matrix:
 [[  61  496]
 [ 118 1123]]
Confusion Matrix:
 [[  70  487]
 [ 128 1113]]
Confusion Matrix:
 [[  78  479]
 [ 148 1093]]


[I 2025-06-20 10:03:01,559] Trial 3 finished with value: 0.598087924758116 and parameters: {'learning_rate': 1.2891080853479032e-05, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'weight_decay': 0.0, 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.1}. Best is trial 1 with value: 0.6244258260138161.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▇▁
eval/balanced_accuracy,▁█▆
eval/cohen_kappa,▁█▆
eval/f1_score,▁██
eval/hamming_loss,▁▂█
eval/jaccard,▁██
eval/loss,█▂▁
eval/mcc,▁█▅
eval/precision,▁█▄
eval/recall,█▇▁
eval/runtime,█▃▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.676400,0.688437,0.565932,0.688543,0.579736,0.688543,0.003611,0.500276,0.000756,0.346675,0.311457,36.754200,48.920000,6.122000
2,0.623100,0.641949,0.603349,0.655172,0.593978,0.655172,0.043505,0.515683,0.037442,0.378275,0.344828,36.762000,48.909000,6.120000
3,0.544900,0.682245,0.599536,0.679088,0.610746,0.679088,0.061810,0.516680,0.042563,0.374827,0.320912,36.777200,48.889000,6.118000
4,0.455700,0.753007,0.611894,0.682981,0.625838,0.682981,0.092020,0.526922,0.067714,0.386726,0.317019,36.784900,48.879000,6.117000
5,0.261100,0.832964,0.620084,0.631257,0.612631,0.631257,0.093264,0.543876,0.092369,0.400164,0.368743,36.776600,48.890000,6.118000
6,0.153100,0.931243,0.624914,0.640156,0.616316,0.640156,0.101008,0.546365,0.099261,0.404235,0.359844,36.778900,48.887000,6.118000


Confusion Matrix:
 [[   3  554]
 [   6 1235]]
Confusion Matrix:
 [[  83  474]
 [ 146 1095]]
Confusion Matrix:
 [[  50  507]
 [  70 1171]]
Confusion Matrix:
 [[  65  492]
 [  78 1163]]
Confusion Matrix:
 [[175 382]
 [281 960]]
Confusion Matrix:
 [[167 390]
 [257 984]]


[I 2025-06-20 10:39:47,017] Trial 4 finished with value: 0.6249135308938691 and parameters: {'learning_rate': 3.329432327516572e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 16, 'weight_decay': 0.01, 'lora_r': 32, 'lora_alpha': 64, 'lora_dropout': 0.05}. Best is trial 4 with value: 0.6249135308938691.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▄▇▇▁▂
eval/balanced_accuracy,▁▃▃▅██
eval/cohen_kappa,▁▄▄▆██
eval/f1_score,▁▅▅▆▇█
eval/hamming_loss,▁▅▂▂█▇
eval/jaccard,▁▅▄▆██
eval/loss,▂▁▂▄▆█
eval/mcc,▁▄▅▇▇█
eval/precision,▁▃▆█▆▇
eval/recall,█▄▇▇▁▂
eval/runtime,▁▃▆█▆▇


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,34.968400,51.418000,6.434000


Confusion Matrix:
 [[ 557    0]
 [1241    0]]


[I 2025-06-20 10:48:41,981] Trial 5 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁
eval/samples_per_second,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.906200,1.338670,0.571000,0.690768,0.644350,0.690768,0.042203,0.503866,0.010580,0.350996,0.309232,36.817600,48.835000,6.111000
2,1.098000,0.979894,0.574944,0.680756,0.580129,0.680756,0.008700,0.501562,0.004166,0.353237,0.319244,36.807400,48.849000,6.113000


Confusion Matrix:
 [[   7  550]
 [   6 1235]]
Confusion Matrix:
 [[  17  540]
 [  34 1207]]


[I 2025-06-20 11:05:40,339] Trial 6 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▁
eval/balanced_accuracy,█▁
eval/cohen_kappa,█▁
eval/f1_score,▁█
eval/hamming_loss,▁█
eval/jaccard,▁█
eval/loss,█▁
eval/mcc,█▁
eval/precision,█▁
eval/recall,█▁
eval/runtime,█▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,34.934800,51.467000,6.441000


IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Confusion Matrix:
 [[ 557    0]
 [1241    0]]


[I 2025-06-20 11:13:54,944] Trial 7 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁
eval/samples_per_second,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.000000,nan,0.146541,0.309789,0.095969,0.309789,0.000000,0.500000,0.000000,0.154894,0.690211,36.018000,49.919000,6.247000


Confusion Matrix:
 [[ 557    0]
 [1241    0]]


[I 2025-06-20 11:22:03,113] Trial 8 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁
eval/samples_per_second,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.911600,1.343670,0.571283,0.691324,0.658370,0.691324,0.048490,0.504269,0.011691,0.351286,0.308676,36.740700,48.938000,6.124000
2,1.103900,0.979939,0.578462,0.682425,0.592423,0.682425,0.023054,0.504255,0.011329,0.356347,0.317575,36.761300,48.910000,6.121000


Confusion Matrix:
 [[   7  550]
 [   5 1236]]
Confusion Matrix:
 [[  20  537]
 [  34 1207]]


[I 2025-06-20 11:38:57,016] Trial 9 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▁
eval/balanced_accuracy,█▁
eval/cohen_kappa,█▁
eval/f1_score,▁█
eval/hamming_loss,▁█
eval/jaccard,▁█
eval/loss,█▁
eval/mcc,█▁
eval/precision,█▁
eval/recall,█▁
eval/runtime,▁█


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.651100,0.685351,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.727500,48.955000,6.126000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]


[I 2025-06-20 11:44:58,820] Trial 10 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/loss,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.638300,0.755057,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.748100,48.928000,6.123000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]


[I 2025-06-20 11:51:13,148] Trial 11 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/loss,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.671600,0.843381,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.746900,48.929000,6.123000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]


[I 2025-06-20 11:57:28,246] Trial 12 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁
eval/balanced_accuracy,▁
eval/cohen_kappa,▁
eval/f1_score,▁
eval/hamming_loss,▁
eval/jaccard,▁
eval/loss,▁
eval/mcc,▁
eval/precision,▁
eval/recall,▁
eval/runtime,▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.626600,0.621766,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.154600,49.731000,6.223000
2,0.653500,0.628554,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.186700,49.687000,6.218000
3,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.162600,49.720000,6.222000
4,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.170200,49.709000,6.221000
5,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.167600,49.713000,6.221000
6,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.166900,49.714000,6.221000
7,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.166600,49.714000,6.221000
8,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.183500,49.691000,6.218000
9,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.176600,49.701000,6.219000
10,0.000000,nan,0.152392,0.312570,0.786448,0.312570,0.035378,0.502015,0.002500,0.157341,0.687430,36.204600,49.662000,6.215000


Confusion Matrix:
 [[   0  557]
 [   0 1241]]
Confusion Matrix:
 [[   0  557]
 [   0 1241]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]
Confusion Matrix:
 [[ 557    0]
 [1236    5]]


[I 2025-06-20 13:07:00,715] Trial 13 finished with value: 0.1523924214219937 and parameters: {'learning_rate': 8.436324649930204e-05, 'num_train_epochs': 10, 'per_device_train_batch_size': 4, 'weight_decay': 0.01, 'lora_r': 32, 'lora_alpha': 128, 'lora_dropout': 0.0}. Best is trial 4 with value: 0.6249135308938691.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,██▁▁▁▁▁▁▁▁
eval/balanced_accuracy,▁▁████████
eval/cohen_kappa,▁▁████████
eval/f1_score,██▁▁▁▁▁▁▁▁
eval/hamming_loss,▁▁████████
eval/jaccard,██▁▁▁▁▁▁▁▁
eval/loss,▁█
eval/mcc,▁▁████████
eval/precision,▁▁████████
eval/recall,██▁▁▁▁▁▁▁▁
eval/runtime,▁▅▂▃▃▃▃▅▄█


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.707800,0.720169,0.580312,0.685762,0.607494,0.685762,0.038279,0.506672,0.017836,0.358208,0.314238,36.809500,48.846000,6.113000
2,0.626400,0.650472,0.601291,0.650723,0.590237,0.650723,0.036508,0.513449,0.031883,0.376303,0.349277,36.811000,48.844000,6.112000


Confusion Matrix:
 [[  20  537]
 [  28 1213]]
Confusion Matrix:
 [[  85  472]
 [ 156 1085]]


[I 2025-06-20 13:22:03,217] Trial 14 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,█▁
eval/balanced_accuracy,▁█
eval/cohen_kappa,▁█
eval/f1_score,▁█
eval/hamming_loss,▁█
eval/jaccard,▁█
eval/loss,█▁
eval/mcc,█▁
eval/precision,█▁
eval/recall,█▁
eval/runtime,▁█


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.624900,0.631577,0.570172,0.681869,0.568310,0.681869,-0.003916,0.499399,-0.001619,0.349389,0.318131,36.754800,48.919000,6.122000
2,0.632800,0.617914,0.563707,0.690211,0.476392,0.690211,0.000000,0.500000,0.000000,0.345106,0.309789,36.522100,49.230000,6.161000


Confusion Matrix:
 [[  11  546]
 [  26 1215]]
Confusion Matrix:
 [[   0  557]
 [   0 1241]]


[I 2025-06-20 13:34:20,906] Trial 15 pruned. 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁█
eval/balanced_accuracy,▁█
eval/cohen_kappa,▁█
eval/f1_score,█▁
eval/hamming_loss,█▁
eval/jaccard,█▁
eval/loss,█▁
eval/mcc,▁█
eval/precision,█▁
eval/recall,▁█
eval/runtime,█▁


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.711500,0.660392,0.580234,0.657953,0.566129,0.657953,-0.010640,0.496917,-0.007769,0.356236,0.342047,36.735000,48.945000,6.125000
2,0.622600,0.692499,0.603979,0.637375,0.591307,0.637375,0.041488,0.517138,0.038851,0.379941,0.362625,36.769200,48.900000,6.119000
3,0.509000,0.818347,0.609766,0.675195,0.613973,0.675195,0.075686,0.523755,0.058870,0.384535,0.324805,36.780600,48.884000,6.117000
4,0.414500,1.241546,0.618168,0.679088,0.624415,0.679088,0.097129,0.531523,0.077503,0.392955,0.320912,36.791000,48.871000,6.116000
5,0.089000,1.327863,0.625216,0.645161,0.615814,0.645161,0.098762,0.544054,0.095991,0.403573,0.354839,36.782200,48.882000,6.117000


Confusion Matrix:
 [[  41  516]
 [  99 1142]]
Confusion Matrix:
 [[ 112  445]
 [ 207 1034]]
Confusion Matrix:
 [[  70  487]
 [  97 1144]]
Confusion Matrix:
 [[  80  477]
 [ 100 1141]]
Confusion Matrix:
 [[ 155  402]
 [ 236 1005]]


[I 2025-06-20 14:10:25,093] Trial 16 finished with value: 0.625216398414874 and parameters: {'learning_rate': 3.108516558929903e-05, 'num_train_epochs': 5, 'per_device_train_batch_size': 4, 'weight_decay': 0.03, 'lora_r': 32, 'lora_alpha': 96, 'lora_dropout': 0.15000000000000002}. Best is trial 16 with value: 0.625216398414874.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▄▁▇█▂
eval/balanced_accuracy,▁▄▅▆█
eval/cohen_kappa,▁▄▅▇█
eval/f1_score,▁▅▆▇█
eval/hamming_loss,▅█▂▁▇
eval/jaccard,▁▅▅▆█
eval/loss,▁▁▃▇█
eval/mcc,▁▄▇██
eval/precision,▁▄▇█▇
eval/recall,▄▁▇█▂
eval/runtime,▁▅▇█▇


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.746800,0.703161,0.578381,0.577864,0.578906,0.577864,0.015306,0.507672,0.015306,0.361298,0.422136,36.738100,48.941000,6.124000
2,0.641900,0.680601,0.620950,0.661290,0.613719,0.661290,0.087407,0.533968,0.078997,0.396585,0.338710,36.738600,48.940000,6.124000
3,0.482300,0.764933,0.613433,0.676307,0.617998,0.676307,0.084351,0.527035,0.066670,0.388186,0.323693,36.747600,48.928000,6.123000
4,0.446900,1.112404,0.615711,0.677976,0.621489,0.677976,0.090978,0.529233,0.072048,0.390473,0.322024,36.762300,48.909000,6.120000
5,0.121800,1.149163,0.627747,0.651835,0.618460,0.651835,0.103515,0.544930,0.099402,0.405502,0.348165,36.764000,48.906000,6.120000


Confusion Matrix:
 [[180 377]
 [382 859]]
Confusion Matrix:
 [[ 111  446]
 [ 163 1078]]
Confusion Matrix:
 [[  75  482]
 [ 100 1141]]
Confusion Matrix:
 [[  77  480]
 [  99 1142]]
Confusion Matrix:
 [[ 147  410]
 [ 216 1025]]


[I 2025-06-20 14:49:13,118] Trial 17 finished with value: 0.6277470280482499 and parameters: {'learning_rate': 3.01535441854931e-05, 'num_train_epochs': 5, 'per_device_train_batch_size': 4, 'weight_decay': 0.02, 'lora_r': 16, 'lora_alpha': 48, 'lora_dropout': 0.15000000000000002}. Best is trial 17 with value: 0.6277470280482499.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-2-7b-hf and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


eval/accuracy,▁▇██▆
eval/balanced_accuracy,▁▆▅▅█
eval/cohen_kappa,▁▆▅▆█
eval/f1_score,▁▇▆▆█
eval/hamming_loss,█▂▁▁▃
eval/jaccard,▁▇▅▆█
eval/loss,▁▁▂▇█
eval/mcc,▁▇▆▇█
eval/precision,▁▇▇██
eval/recall,▁▇██▆
eval/runtime,▁▁▄██


Epoch,Training Loss,Validation Loss,F1 Score,Accuracy,Precision,Recall,Mcc,Balanced Accuracy,Cohen Kappa,Jaccard,Hamming Loss,Runtime,Samples Per Second,Steps Per Second
1,0.812300,0.743670,0.592421,0.657953,0.582884,0.657953,0.019563,0.506318,0.015551,0.367517,0.342047,36.759700,48.912000,6.121000
2,0.699500,0.691512,0.605065,0.660734,0.598309,0.660734,0.050955,0.517733,0.042791,0.379901,0.339266,36.736600,48.943000,6.125000


Confusion Matrix:
 [[  60  497]
 [ 118 1123]]
Confusion Matrix:
 [[  79  478]
 [ 132 1109]]


In [ ]:
# Re-training the model with the best hyperparameters
best_hps = best_run.hyperparameters

# Re-initialize the base model
final_base_model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label={0: "female", 1: "male"},
    label2id={"female": 0, "male": 1},
    cache_dir=peft_cache_path,
    device_map="auto"
)

final_base_model.config.pad_token_id = tokenizer.pad_token_id

# Re-create the LoRA configuration using the best 'r', 'lora_alpha', 'lora_dropout'
final_lora_config = LoraConfig(
    r=best_hps["lora_r"],
    lora_alpha=best_hps["lora_alpha"],
    lora_dropout=best_hps["lora_dropout"],
    bias="none",
    task_type=TaskType.SEQ_CLS,
    target_modules=target_modules
)

# Apply PEFT to the final base model
final_peft_model = get_peft_model(final_base_model, final_lora_config)
final_peft_model.print_trainable_parameters()

# Define TrainingArguments for the final training run
final_model_output_dir = "../scratch/final_llama2_degendered_model"
final_training_args = TrainingArguments(
    output_dir=final_model_output_dir,
    per_device_train_batch_size=best_hps["per_device_train_batch_size"],
    per_device_eval_batch_size=best_hps["per_device_train_batch_size"],
    num_train_epochs=best_hps["num_train_epochs"],
    learning_rate=best_hps["learning_rate"],
    weight_decay=best_hps["weight_decay"],
    fp16=True,
    save_strategy="epoch",
    logging_steps=50,
    report_to="wandb",
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="f1_score",
    evaluation_strategy="epoch",
    save_total_limit=1,
    run_name="final_model_training_best_hps"
)

# Initialize the Trainer for final training
final_trainer = Trainer(
    model=final_peft_model,
    args=final_training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train the final model
final_trainer.train()

# Evaluate the final (best) model
eval_results = final_trainer.evaluate()
print("\nFinal Model Evaluation Results:")
print(eval_results)

# Save the final trained PEFT model and tokenizer
final_trainer.save_model(final_model_output_dir)
tokenizer.save_pretrained(final_model_output_dir)

print(f"\nFinal model and tokenizer saved to: {final_model_output_dir}")
